#!/usr/local/bin/python3

import argparse
import os
import re

from PIL import Image

def create_image(size=None, color=None):
    if not(size and color):
        return

    img = Image.new('RGB', size, color)
    return img

def save_image(image, path):
    if path:
        path = os.path.abspath(path) + '/image.png'
    else:
        path = os.getcwd() + '/image.png'

    image.save(path)


def generate_image(args):
    if args.size and args.color:
        size = tuple(int(x) for x in tuple(args.size.split(',')))

        if re.match('^#.*', args.color):
            color = tuple(int(args.color[i:i+2], 16) for i in (1, 3, 4))
        else:
            color = args.color

    save_image(create_image(size, color), args.path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--size', help='Size of the image in LxB', type=str)
    parser.add_argument('--path', help='Path to the file', type=str)
    parser.add_argument('--color', help='Color', type=str)
    parser.add_argument('--imgur', help='Upload image to imgur and return URL', type=str)
    args = parser.parse_args()
    generate_image(args)

main()

